config/routes.rb
Rails.application.routes.draw do
  resources :topics, path: '/', only: [:index, :create] do
    resources :comments, only: [:index, :create]
  end
end

app/models/topic.rb
class Topic
  include Paginator
  include Mongoid::Document

  field :created_at, type: DateTime, default: -> { DateTime.now }
  field :name
  field :comments_count, type: Integer, default: -> { 0 }

  validates :name, presence: true

  has_many :comments, dependent: :delete
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  PER_PAGE = 10

  caches_action :index,
    cache_path: Proc.new { "topics/#{params[:p].to_i}/#{cache_key(:topics)}" },
    if: Proc.new { flash[:info].blank? && flash[:danger].blank? }

  def index
    @topics_count = Topic.count
    @comments_count = Comment.count

    @current_page, @total_pages, @topics = Topic.paginate(
      page: params[:p],
      batch_size: PER_PAGE,
      records_count: @topics_count,
      sorting_algorithm: [{id: :desc}, {id: :asc}]
    )
  end

  def create
    @topic = Topic.new
    @topic.name = params[:name]
    if @topic.save
      flash[:info] = "Novo assunto cadastrado!"
      reset_cache_key(:topics)
    else
      flash[:danger] = "Ops, informe o assunto para iniciar uma discussão..."
    end
    redirect_to topics_path
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def count_comments_for(topic)
    counter = topic.comments_count
    case counter
    when 0
      'nenhum comentário'
    when 1
      '1 comentário'
    else 
      "#{counter} comentários"
    end
  end
end

app/views/topics/index.html.erb
<h1>Fórum</h1>

<% @topics.each do |topic| %>
  <p><%= link_to "#{format_datetime topic.created_at} - #{topic.name}", topic_comments_path(topic) %> (<%= count_comments_for(topic) %>)<p>
<% end %>

<%= paginator @current_page, @total_pages %>

<h2>Inicie uma nova discussão</h2>
<%= form_tag topics_path do %>
  <textarea name="name"></textarea>
  <input type="submit" value="criar">
<% end %>

<hr>

<p><%= @topics_count %> tópicos, <%= @comments_count %> comentários.</p>